steps:
  # 1) Build image (use Secret Manager secrets injected as env vars)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ava-shop:$SHORT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=$$NEXT_PUBLIC_SUPABASE_URL'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY'
      - '.'

  # 2) Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ava-shop:$SHORT_SHA'

  # 3) Deploy to Cloud Run (runtime env vars here; avoid committing secrets)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # deploy with runtime env and attach secret from Secret Manager (recommended)
        gcloud run deploy $_SERVICE \
          --image gcr.io/$PROJECT_ID/ava-shop:$SHORT_SHA \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "NODE_ENV=production,NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL" \
          --set-secrets "SUPABASE_SERVICE_ROLE_KEY=projects/$PROJECT_ID/secrets/SUPABASE_SERVICE_ROLE_KEY:latest" \
          --project $PROJECT_ID

images:
  - 'gcr.io/$PROJECT_ID/ava-shop:$SHORT_SHA'

# Use Secret Manager (recommended). Replace PROJECT_ID and secret names with your values.
secrets:
  - secretEnv:
      NEXT_PUBLIC_SUPABASE_URL: "projects/PROJECT_ID/secrets/NEXT_PUBLIC_SUPABASE_URL/versions/latest"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "projects/PROJECT_ID/secrets/NEXT_PUBLIC_SUPABASE_ANON_KEY/versions/latest"

substitutions:
  _IMAGE: 'ava-shop'
  _SERVICE: 'ava-shop'
  _REGION: 'europe-west1'
  # Fallback substitutions (if you prefer passing plain values in trigger)
  _NEXT_PUBLIC_SUPABASE_URL: ""
  _FIREBASE_API_KEY: ""
  _SUPABASE_SERVICE_ROLE_KEY: ""

options:
  substitutionOption: ALLOW_LOOSE